Users\Users\Roles\Code\Tables\Roles:
  table: users_users_roles
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    user_id:
      name: user_id
      type: integer
      length: 11
      nullable: false
    role_id:
      name: role_id
      type: integer
      length: 11
      nullable: false
    created_by:
      name: created_by
      type: integer
      length: 11
      nullable: false
    date_created:
      name: date_created
      type: datetime
      nullable: false
    modified_by:
      name: modified_by
      type: integer
      length: 11
      nullable: false
    date_modified:
      name: date_modified
      type: datetime
      nullable: false
  lifecycleCallbacks:
    prePersist:
      - onPrePersist
      - onPrePersistCallbacks
    preUpdate:
      - onPreUpdate
      - onPreUpdateCallbacks
