Users\Roles\Code\Tables\Roles:
  table: users_roles
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      name: title
      type: string
      length: 255
      nullable: false
    alias:
      name: alias
      type: string
      length: 255
      nullable: false
    admin_access:
      name: admin_access
      type: integer
      length: 11
      nullable: true
    published:
      name: published
      type: integer
      length: 11
      nullable: true
    created_by:
      name: created_by
      type: integer
      length: 11
      nullable: true
    date_created:
      name: date_created
      type: datetime
      nullable: true
    modified_by:
      name: modified_by
      type: integer
      length: 11
      nullable: true
    date_modified:
      name: date_modified
      type: datetime
      nullable: true
  lifecycleCallbacks:
    prePersist:
      - onPrePersist
      - onPrePersistCallbacks
    preUpdate:
      - onPreUpdate
      - onPreUpdateCallbacks
